### ISSUE TITLE
Upload file to root of raw repo fails

### ISSUE THREAD

**Issue by cyrilleverrier** [thiagofigueiro/nexus3-cli#66]
`test-raw-repo` is a new empty raw repository in Nexus3

```
virtualenv --python=python3 env_nexus3cli
source env_nexus3cli/bin/activate

(env_nexus3cli) ➜ pip install nexus3-cli
Successfully installed nexus3-cli-2.0.0

(env_nexus3cli) ➜ touch test.txt

(env_nexus3cli) ➜  ~ nexus3 upload test.txt test-raw-repo
Uploading test.txt to test-raw-repo
Traceback (most recent call last):
  File "/home/cyrille/env_nexus3cli/bin/nexus3", line 10, in <module>
    sys.exit(main())
  File "/home/cyrille/env_nexus3cli/lib/python3.7/site-packages/nexuscli/cli/__init__.py", line 98, in main
    return _run_root_commands(arguments)
  File "/home/cyrille/env_nexus3cli/lib/python3.7/site-packages/nexuscli/cli/__init__.py", line 68, in _run_root_commands
    return command_method(client, arguments)
  File "/home/cyrille/env_nexus3cli/lib/python3.7/site-packages/nexuscli/cli/root_commands.py", line 100, in cmd_upload
    recurse=(not args.get('--norecurse')))
  File "/home/cyrille/env_nexus3cli/lib/python3.7/site-packages/nexuscli/nexus_client.py", line 418, in upload
    recurse=recurse, flatten=flatten)
  File "/home/cyrille/env_nexus3cli/lib/python3.7/site-packages/nexuscli/nexus_client.py", line 390, in _upload_dir_or_file
    repository.upload_file(src_dir, dst_dir, dst_file)
  File "/home/cyrille/env_nexus3cli/lib/python3.7/site-packages/nexuscli/api/repository/model.py", line 291, in upload_file
    upload_method(self, src_file, dst_dir, dst_file)
  File "/home/cyrille/env_nexus3cli/lib/python3.7/site-packages/nexuscli/api/repository/upload.py", line 21, in upload_file_raw
    'Destination path does not contain a directory, which is '
nexuscli.exception.NexusClientInvalidRepositoryPath: Destination path does not contain a directory, which is required by raw repositories
```

I have tried the following variants:
- nexus3 upload test.txt test-raw-repo
- nexus3 upload test.txt test-raw-repo/
- nexus3 upload ./test.txt test-raw-repo
- nexus3 upload ./test.txt test-raw-repo/
- nexus3 upload test.txt test-raw-repo/test.txt
- nexus3 upload ./test.txt test-raw-repo/test.txt
- nexus3 upload /home/cyrille/test.txt test-raw-repo/test.txt

With a folder in the destination path:
```
(env_nexus3cli) ➜  ~ nexus3 upload /home/cyrille/test.txt test-raw-repo/test/
Uploading /home/cyrille/test.txt to test-raw-repo/test/
Uploaded 1 file to test-raw-repo/test/
```

**Comment by thiagofigueiro** [comment]
When I first implemented this, the mandatory folder was a Nexus 3 requirement.

I'll double-check to see if Nexus still has this restriction (or if I got it wrong back then).

Otherwise, this is working as intended.
